### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by baydam**
We are now able to load markdown version of documentation file in about dialog. Please check that this work for you because I couldn't find out since what version qt markdown is supported.

### CODE REVIEW

**Review by aalex — CHANGES_REQUESTED** [review]
LGTM, except that this will require us to manage the CHANGELOG.md at two locations. That file should only be at one location, at the root of the project.

**Comment by aalex** [comment]
Perhaps we could add a script in the .pro file that simply copies the NEWS file from the root of the project there?

**Comment by baydam** [comment]
I had think about it but NEWS file is not markdown file as far as I know! I suggest to replace NEWS with CHANGELOGS.md and put it it the root folder

**Comment by sofian** [comment]
Looks good to me.

**Comment by aalex** [comment]
NEWS is in RestructuredText. Let's rename it to CHANGELOG.md (with no S at the end) and convert it to Markdown. Can we then use that file from the root of the project directly without copying it?

**Review by aalex — APPROVED** [review]
I will approve it for now, since it's an improvement, indeed. 

Let's do this in a further step: NEWS is in RestructuredText. Let's rename it to CHANGELOG.md (with no S at the end) and convert it to Markdown. Can we then use that file from the root of the project directly without copying it?

**Pull request merged**
