### PR TITLE
Implement OSC with oscpack

### PR DESCRIPTION
**Pull request by aalex**
- Use oscpack
- small cleanup in mapmap.pro
- try to troubleshoot the set color paint bug

### CODE REVIEW

**Comment by aalex** [comment]
This works:

```oscsend localhost 12345 /mapmap/mapping/opacity if 1 0.5```

**Comment by sofian** [comment]
It works on my end.

**Comment by sofian** [comment]
Using Ubuntu 18.04

**Comment by baydam** [comment]
I have an error like `g++: error: src/app/objs/oscreceiver.o: No such file or directory` on compilation

**Comment by baydam** [comment]
It's work now! We just need to remove all files in `src/app/objs` before compiling

**Pull request merged**
