### PR TITLE
Feature undo commands

### PR DESCRIPTION
**Pull request by baydam**
hey guys check if I did not do anything before merge it

### CODE REVIEW

**Comment by aalex** [comment]
Looks good! A few random notes:
* We usually put the files in the .pro file in alphabetical order, if it works. (we will fix this minor styling thing later)
* You can add yourself as an author whenever you edit a file. Good.
* Hmm, eventually we should get rid of the commented out "spreadsheet" thing in the MainWindow.cpp.
* Hmm, yeah, the MainWindow is our controller, it seems, in the Qt world. That's how things work it seems. Ok.

**Comment by aalex** [comment]
Oh, and we should test it on OS X.

**Comment by baydam** [comment]
So from now I can think about how to Implement the copy paste feature if it is urgent

@bay_dam

**Comment by aalex** [comment]
For mappings only, for now. That would be soooo great!

2015-01-21 16:46 GMT-05:00 Bay Dam <notifications@github.com>:

> So from now I can think about how to Implement the copy paste feature if
> it is urgent
>
> @bay_dam
>
> On Wed, Jan 21, 2015 at 3:48 PM, Alexandre Quessy
> <notifications@github.com> wrote:
>
> > Oh, and we should test it on OS X.
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/mapmapteam/mapmap/pull/116#issuecomment-70860977
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapmapteam/mapmap/pull/116#issuecomment-70928106>.
>



-- 
Alexandre Quessy - 亚历山大 - ألكسندر
http://alexandre.quessy.net - Artiste en nouveaux médias
http://perte-de-signal.org - Membre de Perte de signal
http://sourcelibre.net - Développement logiciel Web et nouveaux médias
http://labalab.ca - Impliqué dans LabàLab - communauté de pratique en arts
numériques

**Comment by aalex** [comment]
It segfaults for me in main.cpp on line 120.

**Comment by baydam** [comment]
Just comment startOscReceiver call method on MainWindow.cpp at line 200 and see what happen

**Comment by baydam** [comment]
Fixed at 4d6caf2

**Comment by aalex** [comment]
It still segfaults here. 

#0  0x00007ffff5a31d30 in QObject::thread() const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x00007ffff5a3ad65 in QObject::QObject(QObjectPrivate&, QObject*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007ffff6806f53 in QAction::QAction(QObject*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff6b6bc14 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff6b6c760 in QUndoStack::createUndoAction(QObject*, QString const&) const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x000000000042768a in MainWindow::createActions (this=0x7fffffffda10) at MainWindow.cpp:1280
#6  0x000000000041fdb6 in MainWindow::MainWindow (this=0x7fffffffda10) at MainWindow.cpp:51
#7  0x0000000000460ee3 in main (argc=1, argv=0x7fffffffddc8) at main.cpp:120

**Comment by baydam** [comment]
Ok I think that because I use Qt 5.4 and also change #include QtGui to QtWidgets. Try to change that by your side and look

**Comment by baydam** [comment]
Fixed 6a3545f

**Comment by koyach** [comment]
Issues with a Qt version bump can proliferate. We fixed one today on the OS X build script. I think a Issue for documenting and testing the bump would be good.

And I think this should be merged into devel :)

**Pull request merged**
